---
- name: Installing prometheus
  ansible.builtin.include_tasks: prometheus.yml
  when: install_prometheus == True

- name: Installing alertmanger
  ansible.builtin.include_tasks: alertmanager.yml
  when: install_alertmanager == True

- name: Installing grafana
  ansible.builtin.include_tasks: grafana.yml
  when: install_grafana == True
  